### ISSUE TITLE
Version shows 'vnull'

### ISSUE THREAD

**Issue by panther2** [triplea-maps/middle_earth-map_skin2#1]
![middleearth](https://cloud.githubusercontent.com/assets/20812775/18240395/b82874cc-734b-11e6-9ca5-f276828e0f39.jpg)

**Comment by DanVanAtta** [comment]
There was a missing version attribute in the triplea_maps.yaml file for this skin. Should be fixed after: https://github.com/triplea-game/triplea/pull/1204

**Comment by panther2** [comment]
Fixed and closed, thanks.

**Comment by DanVanAtta** [comment]
@panther2 the testing effort has been really helpful, keep it up, thank you!
